CREATE TABLE city (
  id INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
  name TEXT(150) DEFAULT NULL,
  country TEXT(5) DEFAULT NULL,
  latitude TEXT(20) DEFAULT NULL,
  longitude TEXT(20) DEFAULT NULL
);
CREATE TABLE company (
  id INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , 
  company_name VARCHAR UNIQUE , 
  url varchar
);
CREATE TABLE job (
  id INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
  title TEXT(150) DEFAULT NULL,
  telecommute INTEGER NOT NULL  DEFAULT 0,
  date_posted TEXT DEFAULT NULL,
  guid TEXT(150) DEFAULT NULL, 
  id_company INTEGER DEFAULT NULL REFERENCES company (id)
);
CREATE TABLE job_city (
  id INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
  id_job INTEGER DEFAULT NULL REFERENCES job (id),
  id_city INTEGER DEFAULT NULL REFERENCES city (id)
);
CREATE TABLE job_tag (
  id INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , 
  id_job INTEGER  REFERENCES job (id), 
  id_tag INTEGER REFERENCES tag (id)
);
CREATE TABLE tag (
  id INTEGER PRIMARY KEY  NOT NULL ,
  tag VARCHAR,
  language INTEGER DEFAULT (0) 
);
